"""EvacOS-MA Multi-Agent Schema Definitions.

Frozen types for Phase 2+. Re-export everything from sub-modules for flat imports.
"""

from evacos_ma.schemas.multi_agent import (
    REWARD_SCHEMA_VERSION,
    PROMPT_TEMPLATE_VERSION,
    TRACE_SCHEMA_VERSION,
    # ID types
    EpisodeId,
    RoundId,
    BuildingId,
    AgentId,
    FloorId,
    RoomId,
    CorridorId,
    StairwellId,
    ExitId,
    CivilianGroupId,
    HazardId,
    DirectiveId,
    BeliefId,
    ActionId,
    # Enums
    AgentRole,
    Tier,
    ActionTypeMA,
    DirectivePriority,
    # Nested view types
    RoomView,
    CorridorView,
    StairwellEntryView,
    ExitView,
    CivilianGroupView,
    HazardView,
    FloorSummary,
    StairwellAggregateView,
    ElevatorView,
    ExitQueueView,
    BeliefRollup,
    ActionLogEntry,
    DirectiveOutcome,
    CascadeHintOrNull,
    EscalationRequest,
    # First-class types
    Directive,
    StructuredBelief,
    # Observation envelope
    ObservationEnvelopeMA,
    FloorAgentObservationMA,
    OrchestratorObservationMA,
    InterFloorView,
    RoleObservationMA,
    # Action models
    ActionEnvelopeMA,
    RouteWithinFloorArgs,
    PrioritizeRoomArgs,
    OpenExitArgsMA,
    LockdownRoomArgs,
    ScoutArgs,
    PredictStateArgs,
    HandoffToOrchestratorArgs,
    RouteBetweenFloorsArgs,
    CallElevatorArgs,
    EvacuateFloorPriorityArgs,
    BroadcastDirectiveArgs,
    OverrideFloorAgentArgs,
    RequestExplanationArgs,
    WaitArgs,
    ActionArgsMA,
    ActionBundleMA,
    # Reward models
    RewardBreakdown,
    RoleReward,
    RewardsByRole,
    # Step result
    ObservationsByRole,
    StepResultMA,
    StepResultInfo,
    # Trace types
    TraceRowCommon,
    EpisodeSummaryRow,
    RoundTraceRow,
    ActionTraceRow,
    RewardTraceRow,
    BeliefAuditRow,
    RationaleAuditRow,
    CurriculumEventRow,
    # Trajectory sample
    TrajectorySample,
)
from evacos_ma.schemas.rewards import (
    RewardBreakdown,
    RoleReward,
    RewardsByRole,
    REWARD_SCHEMA_VERSION as _RSV,
)

__all__ = [
    "REWARD_SCHEMA_VERSION",
    "PROMPT_TEMPLATE_VERSION",
    "TRACE_SCHEMA_VERSION",
    "EpisodeId",
    "RoundId",
    "BuildingId",
    "AgentId",
    "FloorId",
    "RoomId",
    "CorridorId",
    "StairwellId",
    "ExitId",
    "CivilianGroupId",
    "HazardId",
    "DirectiveId",
    "BeliefId",
    "ActionId",
    "AgentRole",
    "Tier",
    "ActionTypeMA",
    "DirectivePriority",
    "RoomView",
    "CorridorView",
    "StairwellEntryView",
    "ExitView",
    "CivilianGroupView",
    "HazardView",
    "FloorSummary",
    "StairwellAggregateView",
    "ElevatorView",
    "ExitQueueView",
    "BeliefRollup",
    "ActionLogEntry",
    "DirectiveOutcome",
    "CascadeHintOrNull",
    "EscalationRequest",
    "Directive",
    "StructuredBelief",
    "ObservationEnvelopeMA",
    "FloorAgentObservationMA",
    "OrchestratorObservationMA",
    "InterFloorView",
    "RoleObservationMA",
    "ActionEnvelopeMA",
    "RouteWithinFloorArgs",
    "PrioritizeRoomArgs",
    "OpenExitArgsMA",
    "LockdownRoomArgs",
    "ScoutArgs",
    "PredictStateArgs",
    "HandoffToOrchestratorArgs",
    "RouteBetweenFloorsArgs",
    "CallElevatorArgs",
    "EvacuateFloorPriorityArgs",
    "BroadcastDirectiveArgs",
    "OverrideFloorAgentArgs",
    "RequestExplanationArgs",
    "WaitArgs",
    "ActionArgsMA",
    "ActionBundleMA",
    "RewardBreakdown",
    "RoleReward",
    "RewardsByRole",
    "ObservationsByRole",
    "StepResultMA",
    "StepResultInfo",
    "TraceRowCommon",
    "EpisodeSummaryRow",
    "RoundTraceRow",
    "ActionTraceRow",
    "RewardTraceRow",
    "BeliefAuditRow",
    "RationaleAuditRow",
    "CurriculumEventRow",
    "TrajectorySample",
]
